# Basics of python 
We're going to learn basic operations with python. More details can be found anywhere on the internet!

- Data type
- Four arithmetic operations
- Variables
- List, Tuple, Dictionary, and set
- Numpy array
- Function
- Loop

## There are four kinds of data types in python.
- Integer... 1, 3, -3, 100, etc...
- Float... 0.35, 0.22, -0.45. 1.509, etc...
- String... "It's sunny!", "Python", etc...
- Complex... 4j, 3+2j, 1+100j, etc...

Usual four arithematic operations can be applied to integer, float, and complex. In the case of string type, addition and multiplication will work, but subtraction and division will not.
The operators for the four arithematic operations are:
- +... Addition
- -... Subtraction
- *... Multiplication
- /... Division

In [1]:
#Example of four arithematic operations
3+3

6

In [2]:
#Addition of strings
"This "+"is "+"an example "+"of a python code."

'This is an example of a python code.'

In [3]:
#We can check the data type by appling type() operator on the values.
type(5)

int

## If we want to show some outputs, print() operator is used.
Usage: print(anything we want to show)

In [4]:
#Without print() operater
#Only the last value is shown.
5+5
3-2
4*3
5/2

2.5

In [5]:
#With print() operater
#All the outputs are shown now.
print(5+5)
print(3-2)
print(4*3)
print(5/2)

10
1
12
2.5


## Variables
Values can be assigned to variables. We can change the value that a variable holds at any time.

In [6]:
#Assign a value to a variable
x=3
print(x)

3


In [7]:
#Change the value that x ho;ds from 3 to 5
x=5
print(5)

5


## List, tuple, dictionary, and set
Those are used to store more than one value. List, tuple, and dictionary are very much commonly used.
- **list** [value1, value2...] : We can store or remove any types of values. 
- **tuple** (value1, value2...) : We can't remove or add values once it's formed.
- **dictionary** {"Name of value1": value1, "Name of value2": value2...} : Each elements can be accessed by specifing the name of it.
- set {value1, value2...} : Similar to the list, but duplicated values are not allowed. 

The elements in list or tuple can be accessed by specifying the location by integers. **The python starts counting from 0.** <br>
If we want to know what a data type is, type() operatior tells us that information.

In [3]:
#List
list_example=[1,2,3,4]
print(list_example)
print(type(list_example))

[1, 2, 3, 4]
<class 'list'>


In [4]:
#We can add values to a list by using ".append()".
list_example.append(5) #"5" is added to the end of the list.
list_example

[1, 2, 3, 4, 5]

In [9]:
#Tuple
tuple_example=(1,2,3,4)
print(tuple_example)
print(type(tuple_example))

(1, 2, 3, 4)
<class 'tuple'>


In [10]:
#dictionary
dictionary_example={"a":[1,2],"b":[3,4],"c":[5,6]}
print(dictionary_example)
print(dictionary_example["a"])
print(type(dictionary_example))

{'a': [1, 2], 'b': [3, 4], 'c': [5, 6]}
[1, 2]
<class 'dict'>


In [11]:
#set
set_example={1,2,3,4}
print(set_example)
print(type(set_example))

{1, 2, 3, 4}
<class 'set'>


In [12]:
#Access the elements of the list.
#Same for the tuple.
print(list_example[0]) #The first element
print(list_example[2]) #The third element

1
3


## Numpy array
The numpy array is one of the most important concepts in python. Once we convert data into numpy array format, almost all the operations can be applied. It is similar to a usual matrix we learn in linear algebra.
We use numpy module to make a numpy array. The numpy module is a collection of mathematical operations we use in python. "np" is the usual notation of numpy module. 

In [13]:
#Import the numpy module as a name of "np".
import numpy as np

In [14]:
numpyArray_example=np.array([[1,2,3,4],
                            [5,6,7,8],
                            [9,10,11,12]])
print(numpyArray_example)
print(type(numpyArray_example))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>


In [15]:
#We can see the dimension of a numpy aray by using .shape suffix to the array.
print(numpyArray_example.shape) # The output of (3,4) means that the array has three rows and four columns.

(3, 4)


In [16]:
#The elements inside the array can be accessed by specifing the coordinate of it.
#Be careful that the python starts counting from 0, so the coordinate of the upper left corner of the array is (0,0),
print(numpyArray_example[1,2]) #The output is in the second row and the third column.

7


Addition or subtraction among numpy arrays is possible as a similar way to the usual linear algebra. Multiplication and division of numpy arrays by a scalar is also valid.  

In [17]:
#Addition of two numpy arrays.
array_A=np.array([[1,1,1],
                 [2,2,2]])
array_B=np.array([[2,2,2],
                 [3,3,3]])

array_C=array_A+array_B 
array_D=array_A-array_B 
print(array_C)
print(array_D)

[[3 3 3]
 [5 5 5]]
[[-1 -1 -1]
 [-1 -1 -1]]


In [18]:
#Multiplication of a numpy array.
array_E=3*array_A
print(array_E) #All the elements of array_A is multiplicated with a facor of three.

[[3 3 3]
 [6 6 6]]


## Function
We can define a function as a collection of operations we want to apply to numbers, lists, numpy arrays, and so on. Since python uses indent as a way of constructing tools of programs, we need to be very careful with the indentation.

### The basic form of a function in python is:
def [function name](variable name):<br>
(indent) operations

In [19]:
#Define a function that returs a a value multiplied by a factor of 2 of an input value.
def function_example(x):
    y=2*x #Calculate an output (y) as a value multiplied by a factor of 2 of an input value (x).
    return y #Return y as an output of the function.

In [20]:
output=function_example(4)
print(output) #8=2*4

8


In [21]:
#We can use any notations as input values for a function. 
#Input values more than one are also possible.
def function_multipleInputs_example(x1,x2):
    y=x1*x2 #Calculate a product of input values.
    return y

In [22]:
output=function_multipleInputs_example(2,3)
print(output) #6=2*3

6


## Loop
A loop, or for-loop is used when we want to automate operations. Python is known to be very slow when we use too many loops, so the loop operations shoudn't be combined too much.

### The basic form of a loop in python is:
for (index) in (the target values of index):<br>
(indent) operations

If the target values of index is a sequens of values, range() operation is useful. It returns a sequence of values from the start to the end. Be careful of setting the end value since **the end value itself is not included in the sequence**.<br>
**How to use**: range(start, end, step) 
If the start value and step value are not set, they are assumued to be 0 and 1, respectively.

In [23]:
#Define a loop that returns a sequence of integers multiplied by a factor of 3.
#"i" is a common notation of the index.
valueList=[0,1,2,3,4,5,6,7]
for i in valueList:
    y=3*i
    print(y)

0
3
6
9
12
15
18
21


In [24]:
#Same loop as the precious example.
for i in range(0,8): #The end value is set to "8" since we want to get a sequence of integers from 0 to 7.
    y=3*i
    print(y)

0
3
6
9
12
15
18
21


#### In the next tutorial, we'll learn how to handle satellite products with python.